# Generated by Django 4.1.2 on 2022-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustName', models.CharField(max_length=50, unique=True)),
                ('CustEmail', models.CharField(max_length=50, unique=True)),
                ('CustPhnno', models.CharField(max_length=10)),
                ('CustAge', models.CharField(max_length=3)),
                ('CustBatch', models.CharField(max_length=50)),
                ('CustPswd', models.CharField(max_length=50)),
                ('PaymentDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
