# Generated by Django 4.1.4 on 2022-12-13 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ba_tch', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustAge',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PaymentDate',
            field=models.DateField(),
        ),
    ]
