# Generated by Django 4.1.4 on 2022-12-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_site', '0002_payment_customer_list_alter_customer_custage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='list',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yoga_site.customer'),
        ),
    ]
